-- Read-only deployed Step 4 audit. One result; no raw locations or media.
select jsonb_build_object(
 'tables',(select jsonb_agg(jsonb_build_object('table',c.relname,'rls',c.relrowsecurity) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('gym_locations','verification_sessions','verification_signals','location_checkpoints','achievement_definitions','user_achievements','cosmetic_items','inventory','cosmetic_purchases')),
 'policies',(select jsonb_agg(to_jsonb(p)) from pg_policies p where schemaname='public' and tablename in ('gym_locations','verification_sessions','verification_signals','location_checkpoints','achievement_definitions','user_achievements','cosmetic_items','inventory','cosmetic_purchases')),
 'grants',(select jsonb_agg(jsonb_build_object('role',grantee,'table',table_name,'privilege',privilege_type)) from information_schema.table_privileges where table_schema='public' and table_name in ('gym_locations','verification_sessions','verification_signals','location_checkpoints','achievement_definitions','user_achievements','cosmetic_items','inventory','cosmetic_purchases') and grantee in ('anon','authenticated','PUBLIC')),
 'functions',(select jsonb_agg(jsonb_build_object('name',p.proname,'schema',n.nspname,'security_definer',p.prosecdef,'search_path',p.proconfig,'anon_execute',has_function_privilege('anon',p.oid,'execute'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'execute'))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='public' and p.proname in ('sync_engagement','save_gym','start_verification','submit_verification','cosmetic_action','clear_evidence','remove_gym','advance_quest','save_quest')) or (n.nspname='private' and p.proname in ('core_advance_quest','core_save_quest','unlock_achievements','completion_unlocks'))),
 'catalog_items',(select count(*) from public.cosmetic_items),
 'achievement_definitions',(select count(*) from public.achievement_definitions),
 'duplicate_equipped_slots',(select count(*) from (select user_id,slot from public.inventory where equipped group by user_id,slot having count(*)>1) d),
 'invalid_purchase_ledgers',(select count(*) from public.cosmetic_purchases p left join public.credit_transactions c on c.purchase_id=p.id where p.price>0 and (c.id is null or c.amount<>-p.price or c.user_id<>p.user_id))
) as step_4_verification;
