import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('Step 5 social, profiles, rankings and regression authority',async t=>{
 const db=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333';
 const call=(who,sql,args=[],role='authenticated')=>db.transaction(async tx=>{await tx.exec(`set local role ${role}`);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[who]);return tx.query(sql,args);});
 const privacy={profile_visibility:'public',discoverable:true,show_progress:true,show_attributes:true,show_streak:true,show_achievements:true,show_cosmetics:true,leaderboard_opt_in:true};
 const save=(who,settings=privacy,featured=[])=>call(who,'select public.save_social_profile($1,$2,$3)',[who===a?'Aria':who===b?'Bryn':'Cora',settings,featured]);
 const friend=(who,target,action)=>call(who,'select public.friend_action($1,$2)',[target,action]);
 const profile=async(who,target)=>(await call(who,'select public.rpg_profile($1) r',[target])).rows[0].r;
 const board=async(metric,who=a)=>(await call(who,'select public.rpg_leaderboard($1) r',[metric])).rows[0].r;
 try{
 await db.exec(`create role anon nologin;create role authenticated nologin;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
 for(const f of ['202609130001_step_2_identity.sql','202609130002_step_3_core_engine.sql','202609130003_step_4_engagement.sql','202609130004_step_5_social.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
 for(const id of[a,b,c]){await db.query('insert into auth.users values($1)',[id]);await call(id,"select public.complete_character_setup('Adventurer','Balanced')");await call(id,'select public.sync_daily_quests()');await call(id,'select public.sync_engagement()');}
 await t.test('migration repeatability and private-by-default profiles',async()=>{await db.exec(await readFile(new URL('../supabase/migrations/202609130004_step_5_social.sql',import.meta.url),'utf8'));await assert.rejects(profile(a,b));assert.equal((await profile(a,a)).name,'Adventurer');await save(a);await save(b);await save(c);});
 await t.test('send, duplicate, self, recipient-only accept and participant RLS',async()=>{await friend(a,b,'send');await assert.rejects(friend(b,a,'send'));await assert.rejects(friend(a,a,'send'));await assert.rejects(friend(a,b,'accept'));await assert.rejects(friend(c,b,'accept'));assert.equal((await call(c,'select * from public.friendships')).rows.length,0);await friend(b,a,'accept');assert.equal((await call(a,'select status from public.friendships')).rows[0].status,'accepted');await assert.rejects(friend(a,b,'accept'));});
 await t.test('friends visibility, remove, reject and cancellation transitions',async()=>{await save(b,{...privacy,profile_visibility:'friends'});assert.equal((await profile(a,b)).name,'Bryn');await assert.rejects(profile(c,b));await friend(a,b,'remove');await assert.rejects(profile(a,b));await save(b);await friend(a,b,'send');await friend(b,a,'reject');await assert.rejects(friend(a,b,'send'));await friend(a,c,'send');await assert.rejects(friend(c,a,'cancel'));await friend(a,c,'cancel');await friend(c,a,'send');await friend(a,c,'accept');});
 await t.test('field privacy, discovery, sensitive-data exclusion and forged values',async()=>{await save(b,{...privacy,show_progress:false,show_attributes:false,show_streak:false,show_achievements:false,show_cosmetics:false});const p=await profile(a,b);assert.deepEqual(Object.keys(p).sort(),['class','id','name','own']);await save(b,{...privacy,profile_visibility:'private'});const hall=(await call(a,"select public.social_hall('Bryn') r")).rows[0].r;assert.equal(hall.results.length,0);await assert.rejects(save(a,{...privacy,xp:1000}));await assert.rejects(save(a,privacy,['legendary']));await assert.rejects(call(a,"update public.characters set xp=999"));await assert.rejects(call(a,"insert into public.friendships(user_low,user_high,sender_id,status) values($1,$2,$1,'accepted')",[a,b]));await save(b);});
 await t.test('cosmetic ownership and featured unlock persistence',async()=>{await db.query("insert into public.user_achievements(user_id,achievement_id) values($1,'first_quest')",[a]);await save(a,privacy,['first_quest']);await call(a,"select public.cosmetic_action('frames-0','equip')").catch(async()=>{const item=(await call(a,"select item_id from public.inventory where slot='frames'")).rows[0].item_id;await call(a,"select public.cosmetic_action($1,'equip')",[item]);});const p=await profile(b,a);assert.equal(p.achievements[0].featured_position,1);assert.ok(p.cosmetics.some(x=>x.slot==='frames'));assert.ok(!JSON.stringify(p).includes('latitude'));assert.ok(!JSON.stringify(p).includes('verification_signals'));await assert.rejects(save(a,privacy,['first_quest','first_quest']));});
 await t.test('real verified completion ledger excludes Focus and survives repeat migration',async()=>{
  const make=async(type,owner)=>{const q=(await call(owner,'select public.save_quest(null,$1) id',[{title:'Ledger acceptance',description:'',category:'strength',quest_type:type,recurrence:'once',difficulty:'easy',duration_minutes:5,completion_condition:'Perform the acceptance activity',target_units:1,verification_kind:type==='verified'?'gym':null}])).rows[0].id;const gym=type==='verified'?(await call(owner,"select public.save_gym('Fixture gym',19,72) id")).rows[0].id:null;const s=(await call(owner,'select public.start_verification($1,$2,false) id',[q,gym])).rows[0].id;await db.query("update public.verification_sessions set status='passed',confidence=80 where id=$1",[s]);await db.query("update public.quest_progress set units=1,started_at=now()-interval '10 minutes' where quest_id=$1",[q]);await call(owner,"select public.advance_quest($1,'complete',null)",[q]);return q;};
  await make('verified',a);await make('focus',a);await make('verified',b);
  assert.equal((await call(a,'select count(*)::int n from public.verified_progress')).rows[0].n,1);
  assert.equal((await board('overall_verified_xp')).rows.find(x=>x.id===a).value,10);
  await db.exec(await readFile(new URL('../supabase/migrations/202609130004_step_5_social.sql',import.meta.url),'utf8'));
  assert.equal((await board('overall_verified_xp')).rows.find(x=>x.id===a).value,10);
 });
 await t.test('all seven leaderboards, ties, current rank, UTC week and privacy filters',async()=>{
  const all=await board('overall_verified_xp');assert.equal(all.rows.find(x=>x.id===a).rank,1);assert.equal(all.rows.find(x=>x.id===b).rank,1);assert.equal(all.rows.find(x=>x.id===c).rank,3);assert.equal(all.me.id,a);
  await db.query("update public.verified_progress set completed_at=(date_trunc('week',now() at time zone 'UTC') at time zone 'UTC')-interval '1 second' where user_id=$1",[b]);assert.equal((await board('weekly_verified_xp')).rows.find(x=>x.id===b).value,0);assert.equal(new Date((await board('weekly_verified_xp')).week_start).getUTCDay(),1);
  for(const metric of ['streak','strength','intelligence','focus','discipline'])assert.equal((await board(metric)).rows.length,3);
  await save(b,{...privacy,show_attributes:false});assert.ok(!(await board('strength')).rows.some(x=>x.id===b));await save(a,{...privacy,leaderboard_opt_in:false});assert.equal((await board('overall_verified_xp')).me,null);await save(a);await save(b);
  await db.query("update public.streaks set current_streak=9,longest_streak=9,last_activity_day=(now() at time zone 'UTC')::date-2 where user_id=$1",[b]);assert.equal((await board('streak')).rows.find(x=>x.id===b).value,0);
 });
 await t.test('anonymous and unauthorized RPC/table access denied',async()=>{for(const sql of ["select public.social_hall()","select public.rpg_profile('11111111-1111-4111-8111-111111111111')","select public.rpg_leaderboard('streak')","select private.social_visible('11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222')"])await assert.rejects(call('',sql,[],'anon'));await assert.rejects(call(a,"delete from public.verified_progress"));await assert.rejects(call(b,"insert into public.featured_achievements values($1,'first_quest',1)",[a]));await assert.rejects(board('credits'));await assert.rejects(call(a,'select public.social_hall($1)', ['x'.repeat(61)]));});
 }finally{await db.close();}
});

