'use client';
import {useEffect,useRef,useState,useTransition,useCallback} from 'react';
import {useRouter} from 'next/navigation';
import {Artwork,SheetRegion} from './artwork';
import {assets} from '../lib/assets';
import {verificationAdapters} from '../lib/engagement/adapters';
import type {GameData} from '../lib/game/types';
import type {EngagementData,EngagementResult,EvidenceInput} from '../lib/engagement/types';
import {saveGym,startVerification,submitVerification,removePrivateData} from '../app/engagement/actions';
export function ProofOfAction({data,game,selectedQuest}:{data:EngagementData;game:GameData;selectedQuest:string|null}){
 const router=useRouter();const [questId,setQuestId]=useState('');const [gymId,setGymId]=useState('');const [strong,setStrong]=useState(false);const [name,setName]=useState('');const [lat,setLat]=useState('');const [lon,setLon]=useState('');const [reflection,setReflection]=useState('');const [result,setResult]=useState<EngagementResult>({});const [pending,start]=useTransition();const [sampling,setSampling]=useState(false);const [now,setNow]=useState(0);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const busySample=useRef(false);
 const eligible=game.quests.filter(q=>['focus','verified'].includes(q.quest_type));const chosen=eligible.find(q=>q.id===questId);const progress=game.progress.find(p=>p.quest_id===chosen?.id);const session=data.sessions.find(s=>s.progress_id===progress?.id);const needsLocation=session?.method==='gym'||session?.method==='running';
 useEffect(()=>{if(selectedQuest){setQuestId(selectedQuest);setSampling(false);document.getElementById('proof')?.scrollIntoView({behavior:'smooth'});}},[selectedQuest]);
 useEffect(()=>{if(!questId&&eligible.length)setQuestId(eligible[0].id);},[questId,eligible]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);setNow(Date.now());return()=>clearInterval(t);},[]);
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;},[session?.id,session?.status,session?.paused]);
 const send=useCallback(async(kind:string,evidence:EvidenceInput={})=>{
  if(!session)return;const response=await submitVerification({session:session.id,request:crypto.randomUUID(),kind,data:evidence});setResult(response);router.refresh();return response;
 },[session,router]);
 useEffect(()=>{
  if(!sampling||!session||session.status!=='pending'||session.paused)return;
  const sample=()=>{if(busySample.current)return;if(needsLocation){if(document.visibilityState!=='visible')return;busySample.current=true;navigator.geolocation.getCurrentPosition(async p=>{try{await send('location',{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,visible:document.visibilityState==='visible'});}finally{busySample.current=false;}},async e=>{try{await send('permission',{state:e.code===1?'denied':'unavailable'});}finally{busySample.current=false;setSampling(false);}},{enableHighAccuracy:true,maximumAge:0,timeout:10000});}else{busySample.current=true;void send('heartbeat',{visible:document.visibilityState==='visible'}).finally(()=>{busySample.current=false;});}};
  const visibility=()=>{if(!needsLocation)sample();else if(document.visibilityState!=='visible')void send('pause');};
  const timer=setInterval(sample,15000);document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visibility);};
 },[sampling,session,needsLocation,send]);
 const run=(fn:()=>Promise<EngagementResult|void|undefined>)=>start(async()=>{try{const r=await fn();if(r)setResult(r);router.refresh();}catch{setResult({error:'Unable to reach the service. Retry safely.'});}});
 const coordinates=()=>{if(!navigator.geolocation){setResult({error:'GPS is unavailable in this browser. Enter your gym coordinates manually.'});return;}navigator.geolocation.getCurrentPosition(p=>{setLat(String(p.coords.latitude));setLon(String(p.coords.longitude));setResult({message:`Location received, reported accuracy ${Math.round(p.coords.accuracy)}m. Confirm this is your gym before saving.`});},()=>setResult({error:'Location permission denied or GPS unavailable. You can enter gym coordinates manually.'}),{enableHighAccuracy:true,timeout:10000,maximumAge:0});};
 const enableSignals=()=>{if(needsLocation&&!navigator.geolocation){run(()=>send('permission',{state:'unavailable'}));return;}setSampling(true);if(needsLocation){navigator.geolocation.getCurrentPosition(p=>run(()=>send('location',{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,visible:true})),e=>{setSampling(false);run(()=>send('permission',{state:e.code===1?'denied':'unavailable'}));},{enableHighAccuracy:true,timeout:10000,maximumAge:0});}else run(()=>send('heartbeat',{visible:document.visibilityState==='visible'}));};
 const camera=async()=>{try{if(!navigator.mediaDevices?.getUserMedia){await send('camera',{state:'unavailable'});return;}stream.current?.getTracks().forEach(t=>t.stop());stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});if(video.current)video.current.srcObject=stream.current;await send('camera',{state:'local_preview'});}catch{await send('camera',{state:'denied'});}};
 return <section id="proof" className="rpg-panel proof-panel proof-live"><div className="proof-scene"><Artwork art={assets.verification.scene}/><span>PROOF OF ACTION</span></div><div className="proof-content"><p className="eyebrow">EVIDENCE BEFORE PROGRESSION</p><h2>Proof of Action &amp; Focus</h2><p className="proof-note">Honor: self confirmation. Focus: foreground timer/check-ins. Verified: task-specific browser evidence. Strong Verified: independent signals; unavailable without an attestation provider. No system can make cheating impossible.</p>{!data.ready?<p role="alert">{data.error}</p>:<>
 <label className="evidence-label">Quest context<select value={questId} onChange={e=>{setQuestId(e.target.value);setSampling(false);setResult({});}}>{eligible.map(q=><option key={q.id} value={q.id}>{q.title} · {q.quest_type}</option>)}</select></label>{!chosen&&<p>Create a Verified or Focus quest to begin.</p>}
 {chosen?.quest_type==='verified'&&chosen.verification_kind==='gym'&&<details className="gym-settings"><summary>Choose or save your gym</summary><p className="proof-note">Coordinates are private to your account and used for a fixed 150m geofence. Samples retain only distance/accuracy, not raw coordinates. Location access occurs only when requested.</p><label className="evidence-label">Saved gym<select value={gymId} onChange={e=>setGymId(e.target.value)}><option value="">Select gym</option>{data.gyms.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><button className="rpg-button secondary" disabled={pending||!gymId} onClick={()=>run(()=>removePrivateData(gymId,'gym'))}>Remove Selected Gym</button><label className="evidence-label">Gym name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><div className="quest-fields"><label className="evidence-label">Latitude<input type="number" step="any" min={-90} max={90} value={lat} onChange={e=>setLat(e.target.value)}/></label><label className="evidence-label">Longitude<input type="number" step="any" min={-180} max={180} value={lon} onChange={e=>setLon(e.target.value)}/></label></div><button className="rpg-button secondary" onClick={coordinates}>Request my current location</button><button className="rpg-button" disabled={pending||!name.trim()||lat===''||lon===''} onClick={()=>run(async()=>{const r=await saveGym({name,latitude:Number(lat),longitude:Number(lon)});if(r.id)setGymId(r.id);return r;})}>Save Gym Privately</button></details>}
 {chosen&&(!session||session.status==='failed')&&<><label className="proof-note"><input type="checkbox" checked={strong} onChange={e=>setStrong(e.target.checked)}/> Request Strong Verified (will remain Pending without independent attestation)</label><button className="rpg-button" disabled={pending||(chosen.verification_kind==='gym'&&!gymId)} onClick={()=>run(()=>startVerification({quest:chosen.id,gym:chosen.verification_kind==='gym'?gymId:null,strong}))}>Start {chosen.quest_type==='focus'?'Focus Session':'Verification Session'}</button></>}
 {session&&<><p className="proof-note">{verificationAdapters[session.method].explanation}</p><p className={`verification-status status-${session.status}`} role="status">{session.status.toUpperCase()} · Confidence {session.confidence}/100 · {session.verification_level.replaceAll('_',' ')}</p><div role="timer" aria-label="Remaining required activity" className="focus-clock">{Math.floor(Math.max(0,session.required_seconds-session.active_seconds)/60)}:{String(Math.max(0,session.required_seconds-session.active_seconds)%60).padStart(2,'0')} remaining · saved every sample</div><div className="proof-grid">{[['document','Travel / arrival',session.method==='gym'?(session.arrival_seen?'Arrival observed':'No arrival yet')+' / '+(session.travel_seen?'outside-area sample observed':'no travel signal'):'Not required'],['location','Geofence',session.method==='gym'?(session.inside_area?'Inside, accuracy accepted':'Outside, uncertain or unavailable'):'Not used'],['duration','Active duration',`${session.active_seconds}/${session.required_seconds} seconds`],['checkpoint','Random checkpoint',session.checkpoint_passed?'Passed':now<Date.parse(session.checkpoint_due)?'Will open during this session':now>Date.parse(session.checkpoint_expires)?'Expired':'OPEN · respond now'],['identity','Identity / liveness',`Account signed in; biometric liveness unavailable. Camera: ${session.camera_state}`],['confidence','Dwell',`${session.dwell_seconds}/${Math.min(600,session.required_seconds)} continuous seconds`]].map(([icon,title,value])=><div className="proof-step" key={title}><SheetRegion art={assets.verification[icon as 'location'|'duration'|'checkpoint'|'identity'|'confidence']} decorative/><span>{title}<small>{value}</small></span></div>)}</div><ul className="evidence-reasons">{session.reasons.map(r=><li key={r}>{r}</li>)}</ul><button className="text-link" disabled={pending} onClick={()=>{setSampling(false);run(()=>removePrivateData(session.id,'evidence'));}}>Clear detailed evidence (ends pending session)</button>
 {session.status==='pending'&&<><p className="proof-note">{needsLocation?'Enable GPS to submit foreground location samples every 15 seconds. Poor accuracy cannot pass the geofence. Leaving or long gaps resets continuous dwell.':'Keep this page visible to count focus time. Background gaps are not credited. Other apps are not monitored or blocked.'} Pause stops counting; the checkpoint window still expires. Exit ends this attempt without rewards.</p><div className="evidence-actions"><button className="rpg-button" disabled={pending||sampling||session.paused} onClick={enableSignals}>{sampling?'Signals enabled':needsLocation?'Enable GPS sampling':'Enable foreground timer'}</button><button className="rpg-button secondary" disabled={pending} onClick={()=>{setSampling(false);run(()=>send(session.paused?'resume':'pause'));}}>{session.paused?'Resume':'Pause'}</button><button className="rpg-button secondary" disabled={pending} onClick={()=>{setSampling(false);run(()=>send('exit'));}}>Exit Session</button></div>
 <p className="proof-note">Optional local camera preview: you may check your own movement, but this cannot establish biometric identity. No images or video are uploaded or stored; camera availability does not increase confidence.</p><button className="rpg-button secondary" disabled={pending} onClick={()=>run(camera)}>Open camera locally</button><button className="text-link" onClick={()=>{stream.current?.getTracks().forEach(t=>t.stop());if(video.current)video.current.srcObject=null;}}>Stop Camera</button><video ref={video} autoPlay muted playsInline className="local-camera"/>
 <button className="rpg-button checkpoint-button" disabled={pending||session.checkpoint_passed||now<Date.parse(session.checkpoint_due)||now>Date.parse(session.checkpoint_expires)} onClick={()=>run(()=>send('checkpoint',{challenge:session.challenge}))}>Respond to Random Checkpoint</button>
 <button className="rpg-button secondary" disabled={pending||session.activity_confirmed} onClick={()=>run(()=>send('activity',{confirmed:true}))}>{session.activity_confirmed?'Activity self-confirmed':'I completed the defined activity'}</button>
 {['home_workout','coding','studying','reading'].includes(session.method)&&<><label className="evidence-label">Reflection/check-in (text is not retained)<textarea value={reflection} onChange={e=>setReflection(e.target.value)} minLength={20} maxLength={1000}/></label><button className="rpg-button secondary" disabled={pending||reflection.trim().length<20} onClick={()=>run(()=>send('reflection',{reflection}))}>Submit Reflection Check-in</button></>}
 <button className="rpg-button" disabled={pending} onClick={()=>run(()=>send('final'))}>Run Final Verification</button></>}
 </>}
 </>}{data.ready&&data.sessions.length>0&&<details className="verification-history"><summary>Recent verification results</summary>{data.sessions.slice(0,30).map(v=><p key={v.id}>{game.quests.find(q=>q.id===v.quest_id)?.title??'Archived quest'} · {v.method} · {v.status} · {v.confidence}/100 · {v.started_at.slice(0,10)}</p>)}</details>}{result.error&&<p className="auth-message" role="alert">{result.error}</p>}{result.message&&<p role="status" className="quest-feedback">{result.message}</p>}{result.data?.reward?.xp&&<p className="level-up">Verified completion · +{result.data.reward.xp} XP · +{result.data.reward.credits} credits{result.data.reward.level_up?` · LEVEL UP ${result.data.reward.level}`:''}</p>}</div></section>;
}


