'use client';
import {useEffect,useState,useTransition} from 'react';
import type {GameData} from '../lib/game/types';
import {readQuestHistory} from '../app/quests/actions';
export function QuestHistory({game}:{game:GameData}){
 const [history,setHistory]=useState({completions:game.completions,xpTransactions:game.xpTransactions,creditTransactions:game.creditTransactions});
 const [more,setMore]=useState(game.completions.length===20);const [error,setError]=useState('');const [pending,start]=useTransition();
 useEffect(()=>{setHistory({completions:game.completions,xpTransactions:game.xpTransactions,creditTransactions:game.creditTransactions});setMore(game.completions.length===20);},[game]);
 if(!game.ready)return null;
 return <section className="rpg-panel quest-history" aria-labelledby="history-title"><p className="eyebrow">YOUR DEEDS ENDURE</p><h2 id="history-title">Quest &amp; Reward History</h2><p className="proof-note">Completed quests and their XP, credit and attribute transactions. All dates are UTC.</p>{history.completions.length===0?<p>Your first completed quest will appear here.</p>:<div className="history-scroll"><table><thead><tr><th scope="col">Quest / completed</th><th scope="col">XP / balance</th><th scope="col">Credits / balance</th><th scope="col">Attributes</th></tr></thead><tbody>{history.completions.map(c=>{const xp=history.xpTransactions.find(x=>x.completion_id===c.id),credits=history.creditTransactions.find(x=>x.completion_id===c.id);return <tr key={c.id}><td>{c.quest_snapshot.title}<br/><small>{c.completed_at.slice(0,16).replace('T',' ')} UTC</small>{c.level_after>c.level_before&&<p className="cyan">Level {c.level_before} → {c.level_after}</p>}</td><td className="cyan">+{c.xp}<br/>{xp?`${xp.balance_after} total`:'—'}</td><td className="gold">+{c.credits}<br/>{credits?`${credits.balance_after} total`:'—'}</td><td>{Object.entries(c.attribute_gains).filter(([,n])=>n>0).map(([k,n])=>`${k} +${n}`).join(', ')||'At attribute limits'}</td></tr>;})}</tbody></table></div>}{error&&<p role="alert">{error}</p>}{more&&<button className="rpg-button secondary" disabled={pending} onClick={()=>start(async()=>{setError('');try{const next=await readQuestHistory(history.completions.length);if(!("completions" in next)||!next.completions){setError(next.error??'Unable to load history.');return;}setHistory(h=>({completions:[...h.completions,...next.completions],xpTransactions:[...h.xpTransactions,...next.xpTransactions],creditTransactions:[...h.creditTransactions,...next.creditTransactions]}));setMore(next.completions.length===20);}catch{setError('Connection lost. Please retry.');}})}>{pending?'Loading…':'Load Earlier History'}</button>}</section>;
}

