'use client';

import Link from 'next/link';
import {Bell,ChevronRight,Flame,Home,ScrollText,Swords,Trophy,Sparkles,Users,ShieldCheck,Settings} from 'lucide-react';
import {assets,type CharacterPath} from '@/lib/assets';
import {Artwork,RPGBackground,SheetRegion} from './artwork';
import {LogoutButton} from './logout-button';
import {QuestTracker,RecentGains} from './quest-tracker';
import {QuestHistory} from './quest-history';
import {ProofOfAction} from './proof-of-action';
import {AchievementHall,Treasury} from './treasury';
import {Leaderboards,ProfileManager,SocialHall} from './social';
import type {PlayerData} from '@/lib/supabase/database.types';
import type {GameData} from '@/lib/game/types';
import type {EngagementData} from '@/lib/engagement/types';

type View='command-hall'|'quests'|'character'|'achievements'|'treasury'|'fellowship'|'legends'|'verification'|'profile'|'settings';
const navigation:[View,string,typeof Home][]=[['command-hall','Command Hall',Home],['quests','Quests',ScrollText],['character','Character',Swords],['achievements','Achievements',Trophy],['treasury','Treasury',Sparkles],['fellowship','Fellowship',Users],['legends','Legends',Trophy],['verification','Verification',ShieldCheck],['profile','Profile',Swords],['settings','Settings',Settings]];
const heroForPath:Record<CharacterPath,typeof assets.characters.warrior>={Warrior:assets.characters.warrior,Scholar:assets.characters.scholar,Creator:assets.characters.creator,Balanced:assets.characters.balanced};
const attributes:[string,keyof PlayerData['attributes'],typeof assets.emblems.strength][]=[['Strength','strength',assets.emblems.strength],['Intelligence','intelligence',assets.emblems.book],['Focus','focus',assets.emblems.circuit],['Discipline','discipline',assets.emblems.sword],['Vitality','vitality',assets.emblems.flame],['Charisma','charisma',assets.emblems.crown]];
const pathCopy:Record<CharacterPath,string>={Warrior:'Strength · Vitality · Discipline',Scholar:'Intelligence · Focus · Growth',Creator:'Creativity · Problem solving · Innovation',Balanced:'Balance · Consistency · Growth'};
function Progress({value,label}:{value:number|null;label:string}){return <div className="progress-track" role="progressbar" aria-label={label} aria-valuenow={value??undefined} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${value??0}%`}}/></div>}
function Panel({children,className='',id}:{children:React.ReactNode;className?:string;id?:string}){return <section id={id} className={`rpg-panel ${className}`}><SheetRegion art={assets.decorativeUI.corner} className="panel-ornament" decorative/>{children}</section>}
export function RoutedDashboard({player,game,engagement,view}:{player:PlayerData;game:GameData;engagement:EngagementData;view:View}){
 const path=player.character.class; const format=(n:number)=>n.toLocaleString('en-US');
 const rightRail=<aside className="right-column"><Panel className="identity-panel"><div className="identity-art"><Artwork art={heroForPath[path]}/><div className="identity-shade"/></div><div className="identity-copy"><p className="eyebrow">PLAYER HUD</p><h2>{player.name}</h2><p className="gold">{path} path</p><span className="path-label">Level {player.character.level}</span><Progress value={game.level?.progress_percent??null} label="Level progress"/><small>{game.level?`${format(game.level.current_xp)} / ${format(game.level.next_level_xp)} XP to level ${game.level.level+1}`:'Progression unavailable'}</small><Link href="/profile" className="text-link">View profile <ChevronRight size={14}/></Link></div></Panel><Panel className="attribute-panel"><div className="section-heading"><div><p className="eyebrow">ATTRIBUTES</p><h2>Growth</h2></div></div>{attributes.map(([name,key,art])=>{const value=Number(player.attributes[key]);return <div className="attribute" key={name}><SheetRegion art={art} decorative/><div><span>{name}<b>{value}</b></span><Progress value={value} label={name}/></div></div>})}</Panel><Panel className="treasury-panel gold-panel"><SheetRegion art={assets.rewards.miscellaneous[1]} className="chest" decorative/><p className="eyebrow">TREASURY</p><h2>{format(player.character.credits)} <small>Credits</small></h2><p className="gold">{player.character.streak} day streak</p><Link href="/treasury" className="rpg-button gold-button">Open Treasury<ChevronRight size={14}/></Link></Panel><Panel className="recent-panel"><div className="section-heading"><div><p className="eyebrow">RECENT DEEDS</p><h2>Gains</h2></div></div><RecentGains game={game}/></Panel></aside>;
 const character=<Panel className="character-panel"><div className="section-heading"><div><p className="eyebrow">YOUR CHARACTER</p><h2>{player.name} · {path}</h2></div></div><div className="character-summary"><SheetRegion art={assets.characterPortraits[path]}/><div><h3>{path} path</h3><p>{pathCopy[path]}</p><p className="cyan">Level {player.character.level} · {format(player.character.xp)} total XP</p></div></div><div className="path-grid">{(['Warrior','Scholar','Creator','Balanced'] as CharacterPath[]).map(name=><article key={name} className={`path-card ${name===path?'selected':''}`}><SheetRegion art={assets.characterPaths[name]}/><span><SheetRegion art={assets.characterPortraits[name]}/><span>{name}<small>{name===path?'Current path':'Path overview'}</small></span></span></article>)}</div></Panel>;
 let center:React.ReactNode;
 if(view==='command-hall') center=<><Panel className="command-hero"><RPGBackground art={assets.realms.commandHall}/><div className="hero-copy"><p className="eyebrow">COMMAND HALL</p><h2>Small steps.<br/><em>Big changes.</em></h2><p>Choose your next directive, track your growth, and return stronger.</p><Link href="/quests" className="rpg-button">View Quests<ChevronRight size={16}/></Link></div></Panel><Panel className="route-overview"><p className="eyebrow">SYSTEM OVERVIEW</p><h2>Today&apos;s progress</h2><div className="overview-links"><Link href="/quests">Quest Tracker <ChevronRight size={15}/></Link><Link href="/verification">Proof of Action <ChevronRight size={15}/></Link><Link href="/legends">Hall of Legends <ChevronRight size={15}/></Link></div></Panel></>;
 else if(view==='quests') center=<><QuestTracker game={game} createSignal={0} onEvidence={()=>{location.assign('/verification')}}/><QuestHistory game={game}/></>;
 else if(view==='verification') center=<ProofOfAction data={engagement} game={game} selectedQuest={null}/>;
 else if(view==='achievements') center=<AchievementHall data={engagement}/>;
 else if(view==='treasury') center=<Treasury data={engagement} level={player.character.level} credits={player.character.credits}/>;
 else if(view==='fellowship') center=<SocialHall active/>;
 else if(view==='legends') center=<Leaderboards active/>;
 else if(view==='character') center=character;
 else center=<ProfileManager active engagement={engagement}/>;
 return <main><a className="skip-link" href="#page-content">Skip to content</a><header className="player-hud"><Link href="/command-hall" className="brand" prefetch scroll={false}><SheetRegion art={assets.emblems.sword} decorative/><span><strong>LIFE RPG</strong><small>YOUR REAL LIFE IS THE GAME</small></span></Link><div className="hud-progress"><b>LV. {player.character.level}</b><div><span>{format(player.character.xp)} <small>TOTAL XP</small></span><Progress value={game.level?.progress_percent??null} label="XP to next level"/></div></div><div className="hud-currency"><SheetRegion art={assets.decorativeUI.credits} decorative/><b>{format(player.character.credits)}</b><small>Credits</small></div><div className="hud-streak"><Flame size={17}/><b>{player.character.streak}</b><small>day streak</small></div><button className="icon-button" aria-label="Notifications"><Bell size={18}/></button><Link className="hud-identity" href="/profile" aria-label={`${player.name} profile`} prefetch scroll={false}><SheetRegion art={assets.characterPortraits[path]}/><span>{player.name}<small>{path}</small></span></Link><LogoutButton/></header><div className="shell"><aside className="realm-nav"><p className="eyebrow">NAVIGATION</p><nav aria-label="RPG navigation">{navigation.map(([id,name,Icon])=><Link className={view===id?'active':''} key={id} href={id==='command-hall'?'/command-hall':`/${id}`} prefetch scroll={false}><Icon size={17}/><span>{name}</span><ChevronRight size={12}/></Link>)}</nav><div className="streak-panel"><SheetRegion art={assets.emblems.flame} decorative/><strong>{player.character.streak} <small>DAYS</small></strong><p>Current streak</p></div></aside><div id="page-content" className="realm-content"><div className="dashboard-grid"><div className="main-column">{center}</div>{rightRail}</div></div></div></main>;
}
