'use client';
import {useEffect,useRef,useState,useTransition} from 'react';import {useRouter} from 'next/navigation';
import {RPGBackground,SheetRegion} from './artwork';import {assets,type Art} from '../lib/assets';import type {EngagementData,Cosmetic} from '../lib/engagement/types';import {cosmeticAction} from '../app/engagement/actions';
export function cosmeticArt(item:Pick<Cosmetic,'slot'|'art_index'>):Art{return item.slot==='badges'?assets.achievements[item.art_index]:assets.rewards[item.slot][item.art_index];}
export function AchievementHall({data}:{data:EngagementData}){return <section id="achievements" className="rpg-panel achievement-panel"><div className="section-heading"><div><p className="eyebrow">THE HALL OF HONORS</p><h2>Marks of a Meaningful Life</h2></div><span className="count-label">{data.unlocks.length} UNLOCKED</span></div>{!data.ready?<p>{data.error}</p>:<div className="achievement-grid">{data.achievements.map(a=>{const unlocked=data.unlocks.find(u=>u.achievement_id===a.id);return <article key={a.id} className={`achievement ${unlocked?'':'locked'}`}><SheetRegion art={assets.achievements[a.art_index]}/><h3>{a.title}</h3><span className={unlocked?'gold':'muted'}>{unlocked?'Unlocked':'Locked'}</span><small>{a.description}</small>{unlocked&&<small>{unlocked.unlocked_at.slice(0,10)}</small>}</article>;})}</div>}</section>;}
function Preview({item,close}:{item:Cosmetic;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog className="rpg-dialog" ref={ref} onCancel={close} aria-label={`${item.name} preview`}><div className="dialog-body"><button className="icon-button close-button" onClick={close} aria-label="Close cosmetic preview">×</button><h2>{item.name}</h2><SheetRegion art={cosmeticArt(item)} className="reward-preview"/><p>Cosmetic preview. This grants no ownership or gameplay power.</p><button className="rpg-button secondary" onClick={close}>Close Preview</button></div></dialog>;}
export function Treasury({data,level,credits}:{data:EngagementData;level:number;credits:number}){
 const router=useRouter();const [filter,setFilter]=useState('all');const [preview,setPreview]=useState<Cosmetic|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [pending,start]=useTransition();const [confirm,setConfirm]=useState<Cosmetic|null>(null);
 const act=(item:Cosmetic,action:'buy'|'equip'|'unequip')=>start(async()=>{setError('');try{const r=await cosmeticAction({item:item.id,action});if(r.error)setError(r.error);else{setMessage(r.message??'Saved');setConfirm(null);router.refresh();}}catch{setError('Unable to save. Retry safely.');}});
 return <section id="rewards" className="rpg-panel reward-panel gold-panel"><RPGBackground art={assets.realms.goldCitadel}/><div className="reward-content"><div className="section-heading"><div><p className="eyebrow">THE TREASURY</p><h2>Make Your Legend Your Own</h2></div><span className="gold">{credits} Credits</span></div><p>Cosmetics only. No power boosts. Gems and all relic illustrations are decorative items; credits are the earned currency.</p>{!data.ready?<p role="alert">{data.error}</p>:<><div className="filter-row reward-filters">{['all','owned','equipped','banners','frames','titles','auras','themes','badges','miscellaneous'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div aria-live="polite">{error&&<p className="auth-message" role="alert">{error}</p>}{message&&<p className="quest-feedback">{message}</p>}</div><div className="reward-grid">{data.catalog.filter(i=>filter==='all'||i.slot===filter||filter==='owned'&&data.inventory.some(x=>x.item_id===i.id)||filter==='equipped'&&data.inventory.some(x=>x.item_id===i.id&&x.equipped)).map(i=>{const owned=data.inventory.find(x=>x.item_id===i.id);const locked=level<i.min_level||!!i.required_achievement&&!data.unlocks.some(u=>u.achievement_id===i.required_achievement);return <article className="reward-card" key={i.id}><div className={`reward-art reward-${i.slot}`}><SheetRegion art={cosmeticArt(i)}/></div><div className="reward-copy"><p className="eyebrow">{i.slot} · {i.rarity}</p><h3>{i.name}</h3><div className="reward-state"><span className={owned?.equipped?'cyan':'gold'}>{owned?.equipped?'Equipped':owned?'Owned':locked?'Locked':'Available'}</span>{!owned&&<small>{i.price} Credits</small>}</div>{locked&&<small>Requires level {i.min_level}{i.required_achievement?` and ${data.achievements.find(a=>a.id===i.required_achievement)?.title}`:''}</small>}<button className="rpg-button secondary" onClick={()=>setPreview(i)}>Preview {i.name}</button>{owned?<button className="rpg-button" disabled={pending||locked&&!owned.equipped} onClick={()=>act(i,owned.equipped?'unequip':'equip')}>{owned.equipped?'Unequip':'Equip'}</button>:<button className="rpg-button gold-button" disabled={pending||locked||credits<i.price} onClick={()=>setConfirm(i)}>Acquire Cosmetic</button>}</div></article>;})}</div>
 {confirm&&<div className="delete-confirm" role="alert"><p>Acquire {confirm.name} for {confirm.price} earned credits?</p><button className="rpg-button" disabled={pending} onClick={()=>act(confirm,'buy')}>Confirm Purchase</button><button className="rpg-button secondary" onClick={()=>setConfirm(null)}>Cancel</button></div>}
 {data.purchases.length>0&&<details><summary>Recent cosmetic purchases</summary>{data.purchases.map(p=><p key={p.id}>{data.catalog.find(i=>i.id===p.item_id)?.name} · {p.price} credits · {p.created_at.slice(0,10)}</p>)}</details>}</>}</div>{preview&&<Preview item={preview} close={()=>setPreview(null)}/>}</section>;
}
export function EquippedCosmetics({data}:{data:EngagementData}){const items=data.inventory.filter(x=>x.equipped).flatMap(x=>data.catalog.filter(i=>i.id===x.item_id));return items.length?<div className="equipped-cosmetics" aria-label="Equipped cosmetics">{items.map(i=><span key={i.id} className={`equipped-${i.slot}`}><SheetRegion art={cosmeticArt(i)}/><small>{i.name}</small></span>)}</div>:null;}


