'use server';
import {revalidatePath} from 'next/cache';
import {requireUser} from '../../lib/auth';
import {evidenceSchema,gymSchema,sessionSchema,cosmeticSchema} from '../../lib/engagement/validation';
import type {EngagementResult} from '../../lib/engagement/types';
function safe(message:string){const allowed=['Item is locked','Not enough credits','Own this item before equipping','Choose your saved gym','Session unavailable','Maximum 10 saved locations','Maximum three session attempts per occurrence','Quest already completed','Reflection must be 20 to 1000 characters','Finish or archive your active quest before starting another','The required quest duration has not elapsed','Daily progression limit reached; resume tomorrow (UTC)','Complete the required verification or focus session first','Quest archived'];return allowed.includes(message)?message:'Unable to save. Check the session or migration and retry.';}
export async function saveGym(input:unknown):Promise<EngagementResult>{const p=gymSchema.safeParse(input);if(!p.success)return {error:'Enter a gym name and valid coordinates.'};const {supabase}=await requireUser();try{const {data,error}=await supabase.rpc('save_gym',{p_name:p.data.name,p_lat:p.data.latitude,p_lon:p.data.longitude});if(error)return {error:safe(error.message)};revalidatePath('/');return {id:data,message:'Gym saved privately.'};}catch{return {error:'Connection unavailable.'};}}
export async function startVerification(input:unknown):Promise<EngagementResult>{const p=sessionSchema.safeParse(input);if(!p.success)return {error:'Choose a valid quest and location.'};const {supabase}=await requireUser();try{const {data,error}=await supabase.rpc('start_verification',{p_quest:p.data.quest,p_gym:p.data.gym,p_strong:p.data.strong});if(error)return {error:safe(error.message)};revalidatePath('/');return {id:data,message:'Session started. Enable the required signals.'};}catch{return {error:'Connection unavailable.'};}}
export async function submitVerification(input:unknown):Promise<EngagementResult>{const p=evidenceSchema.safeParse(input);if(!p.success)return {error:'Invalid evidence input.'};const {supabase}=await requireUser();try{const {data,error}=await supabase.rpc('submit_verification',{p_session:p.data.session,p_request:p.data.request,p_kind:p.data.kind,p_data:p.data.data});if(error)return {error:safe(error.message)};revalidatePath('/');return {data:data as EngagementResult['data'],message:p.data.kind==='final'?'Verification evaluated.':undefined};}catch{return {error:'Signal could not be saved. Check connection and retry.'};}}
export async function cosmeticAction(input:unknown):Promise<EngagementResult>{const p=cosmeticSchema.safeParse(input);if(!p.success)return {error:'Invalid cosmetic action.'};const {supabase}=await requireUser();try{const {data,error}=await supabase.rpc('cosmetic_action',{p_item:p.data.item,p_action:p.data.action});if(error)return {error:safe(error.message)};revalidatePath('/');return {message:String(data.message)};}catch{return {error:'Connection unavailable. Retry safely; purchases cannot be duplicated.'};}}

export async function removePrivateData(id:string,kind:'gym'|'evidence'):Promise<EngagementResult>{
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)||!['gym','evidence'].includes(kind))return {error:'Invalid private record.'};
 const {supabase}=await requireUser();try{const {error}=kind==='gym'?await supabase.rpc('remove_gym',{p_gym:id}):await supabase.rpc('clear_evidence',{p_session:id});if(error)return {error:error.message==='Exit the active gym session before removing its location'?error.message:'Unable to remove this private record.'};revalidatePath('/');return {message:'Private details removed. Reward history is retained.'};}catch{return {error:'Connection unavailable.'};}
}
