'use server';
import {requireUser} from '@/lib/auth';
import {revalidatePath} from 'next/cache';
import {friendSchema,profileSchema,searchSchema,boardSchema,idSchema} from '@/lib/social/validation';
import type {Result,Hall,Board,PublicProfile,Privacy} from '@/lib/social/types';
const failure=(message:string)=>message.includes('Could not find the function')?'The social realm is awaiting its database migration.':/Profile unavailable|Player unavailable|Relationship already|Only the|Friendship is not|Please wait|Achievement not|Choose up to|Character setup/.test(message)?message:'The realm could not complete that request. Please retry.';
export async function getSocial(input:unknown):Promise<Result<Hall>>{const p=searchSchema.safeParse(input);if(!p.success)return {error:'Enter a search of up to 60 characters.'};const {supabase}=await requireUser();try{const r=await supabase.rpc('social_hall',{p_query:p.data.query,p_offset:p.data.offset});return r.error?{error:failure(r.error.message)}:{data:r.data as unknown as Hall};}catch{return {error:'Unable to connect. Retry the search.'};}}
export async function getProfile(id:unknown):Promise<Result<PublicProfile>>{const p=idSchema.safeParse(id);if(!p.success)return {error:'Invalid profile.'};const {supabase}=await requireUser();try{const r=await supabase.rpc('rpg_profile',{p_target:p.data});return r.error?{error:failure(r.error.message)}:{data:r.data as unknown as PublicProfile};}catch{return {error:'Profile could not be loaded. Please retry.'};}}
export async function getLeaderboard(input:unknown):Promise<Result<Board>>{const p=boardSchema.safeParse(input);if(!p.success)return {error:'Invalid ranking selection.'};const {supabase}=await requireUser();try{const r=await supabase.rpc('rpg_leaderboard',{p_metric:p.data.metric,p_offset:p.data.offset});return r.error?{error:failure(r.error.message)}:{data:r.data as unknown as Board};}catch{return {error:'Rankings could not be loaded. Please retry.'};}}
export async function changeFriendship(input:unknown):Promise<Result<never>>{const p=friendSchema.safeParse(input);if(!p.success)return {error:'Invalid friendship action.'};const {supabase}=await requireUser();try{const r=await supabase.rpc('friend_action',{p_target:p.data.target,p_action:p.data.action});if(r.error)return {error:failure(r.error.message)};revalidatePath('/');return {message:r.data};}catch{return {error:'Request failed. Refresh before retrying.'};}}
export async function saveProfile(input:unknown):Promise<Result<never>>{const p=profileSchema.safeParse(input);if(!p.success)return {error:'Check your name, privacy choices and up to three unlocked achievements.'};const {supabase}=await requireUser();try{const r=await supabase.rpc('save_social_profile',{p_name:p.data.name,p_privacy:p.data.privacy,p_featured:p.data.featured});if(r.error)return {error:failure(r.error.message)};revalidatePath('/');return {message:r.data};}catch{return {error:'Profile update failed. Please retry.'};}}
export async function getOwnSocial():Promise<Result<{profile:PublicProfile;privacy:Privacy;featured:string[]}>>{const {supabase,user}=await requireUser();try{const [p,s,f]=await Promise.all([supabase.rpc('rpg_profile',{p_target:user.id}),supabase.from('privacy_settings').select('*').eq('user_id',user.id).single(),supabase.from('featured_achievements').select('achievement_id,position').order('position')]);if(p.error||s.error||f.error)return {error:failure(p.error?.message??s.error?.message??f.error?.message??'')};const row=s.data;const privacy:Privacy={profile_visibility:row.profile_visibility,discoverable:row.discoverable,show_progress:row.show_progress,show_attributes:row.show_attributes,show_streak:row.show_streak,show_achievements:row.show_achievements,show_cosmetics:row.show_cosmetics,leaderboard_opt_in:row.leaderboard_opt_in};return {data:{profile:p.data as unknown as PublicProfile,privacy,featured:f.data.map(x=>x.achievement_id)}};}catch{return {error:'Your profile could not be loaded. Please retry.'};}}
